# Generated by Django 5.x on 2026-02-23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("dns", "DNS"), ("tcp", "TCP"), ("tls", "TLS"), ("http", "HTTP")],
                        max_length=10,
                    ),
                ),
                ("target", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "frequency_seconds",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(86400),
                        ],
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "retries",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("consecutive_failures", "Consecutive failures"),
                            ("latency_threshold", "Latency threshold"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "consecutive_failures_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "latency_ms_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(600000),
                        ],
                    ),
                ),
                (
                    "latency_run_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("webhook_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "check_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="checks.check",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="CheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(choices=[("ok", "OK"), ("fail", "Fail")], max_length=10),
                ),
                ("timings_json", models.JSONField(blank=True, default=dict)),
                ("details_json", models.JSONField(blank=True, default=dict)),
                ("error_message", models.CharField(blank=True, default="", max_length=500)),
                (
                    "check_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="checks.check",
                    ),
                ),
            ],
            options={"ordering": ["-started_at", "-id"]},
        ),
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.CharField(max_length=500)),
                (
                    "state",
                    models.CharField(
                        choices=[("triggered", "Triggered"), ("resolved", "Resolved")],
                        max_length=16,
                    ),
                ),
                ("details_json", models.JSONField(blank=True, default=dict)),
                (
                    "check_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_events",
                        to="checks.check",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="checks.alertrule",
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="checkresult",
            index=models.Index(
                fields=["check_ref", "-started_at"], name="chkres_chkref_started_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkresult",
            index=models.Index(fields=["status"], name="chkres_status_idx"),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(fields=["rule", "-created_at"], name="alertev_rule_created_idx"),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["check_ref", "-created_at"], name="alertev_chkref_created_idx"
            ),
        ),
    ]
